name: Main CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build, Test, and Lint
        run: mvn clean verify

      - name: Extract Current Version
        id: extract_version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.CURRENT_VERSION }}"
          release_name: "v${{ env.CURRENT_VERSION }}"
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "target/RESTfulAPIApp-${{ env.CURRENT_VERSION }}.jar" 
          asset_name: "RESTfulAPIApp-${{ env.CURRENT_VERSION }}.jar"
          asset_content_type: application/java-archive

      - name: Bump Patch Version
        id: bump_version
        run: |
          # Split the current version into major, minor, and patch
          IFS='.' read -r major minor patch <<< "${CURRENT_VERSION}"
          
          # Increment the patch version
          patch=$((patch + 1))
          
          # Construct the new version string
          NEW_VERSION="$major.$minor.$patch"

          # Update the version in pom.xml without creating a backup POM
          mvn versions:set -DnewVersion="$NEW_VERSION" -DgenerateBackupPoms=false
          
          # Export the new version as an environment variable
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Acquire Lock
        id: lock
        uses: actions/github-script@v6
        with:
          script: |
            const lockFile = 'version-bump.lock';
            const { data: contents } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: lockFile
            }).catch(() => null);
            
            if (contents) {
              throw new Error('Another version bump is in progress.');
            }
            
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: lockFile,
              message: 'Acquire version bump lock',
              content: Buffer.from('locked').toString('base64'),
              committer: {
                name: 'github-actions',
                email: 'github-actions@github.com'
              },
              author: {
                name: 'github-actions',
                email: 'github-actions@github.com'
              }
            });

      - name: Commit and Push the New Version
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Fetch the latest changes
          git fetch origin main
          
          # Check out the main branch
          git checkout main
          
          # Merge the latest main into the current branch to avoid conflicts
          git merge origin/main

          # Add the updated pom.xml
          git add pom.xml
          
          # Commit the version bump
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          
          # Push the changes
          git push origin main

      - name: Release Lock
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const lockFile = 'version-bump.lock';
            await github.rest.repos.deleteFile({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: lockFile,
              message: 'Release version bump lock',
              sha: (await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: lockFile
              })).data.sha,
              committer: {
                name: 'github-actions',
                email: 'github-actions@github.com'
              },
              author: {
                name: 'github-actions',
                email: 'github-actions@github.com'
              }
            });

      - name: Handle Push Failure
        if: failure()
        run: |
          echo "Push failed due to a conflict. Please retry the workflow."
