name: Main CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21

      - name: Build, Test, and Lint
        run: mvn clean verify

      - name: Bump patch version
        id: bump_version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"

          mvn versions:set -DnewVersion="$NEW_VERSION" -DgenerateBackupPoms=false
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build artifact with new version
        run: mvn clean package

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.NEW_VERSION }}"
          release_name: "v${{ env.NEW_VERSION }}"
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "**/target/*.jar"
          asset_name: "RESTfulAPIApp-${{ env.NEW_VERSION }}.jar"
          asset_content_type: application/java-archive

      - name: Commit and push the new version
        if: ${{ success() }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pom.xml
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git push origin main
