name: Main CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Calculate new version
        id: calculate_version
        run: |
          # Remove the 'v' prefix
          VERSION=${LATEST_TAG#v}
          echo "Latest version: $VERSION"
          
          # Split version into major, minor, and patch
          IFS='.' read -r major minor patch <<< "$VERSION"
          
          # Increment the patch version
          patch=$((patch + 1))
          
          # Construct the new version string
          NEW_VERSION="$major.$minor.$patch"
          
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build, Test, and Lint
        run: mvn clean verify

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.NEW_VERSION }}"
          release_name: "v${{ env.NEW_VERSION }}"
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "target/RESTfulAPIApp-${{ env.NEW_VERSION }}.jar" 
          asset_name: "RESTfulAPIApp-${{ env.NEW_VERSION }}.jar"
          asset_content_type: application/java-archive
